### ISSUE TITLE
configure the three.min.js and viewer3D.min.js locally

### ISSUE THREAD

**Issue by RollingEggOL** [Autodesk-Forge/viewer-javascript-offline.sample#7]
Hi, I want to configure the project locally, replace the codes:
<script src="https://developer.api.autodesk.com/modelderivative/v2/viewers/three.min.js"></script>
    <script src="https://developer.api.autodesk.com/modelderivative/v2/viewers/viewer3D.min.js?v=v3.3"></script>

with 

<script src="./three.min.js"></script>
<script src="./viewer3D.min.js"></script>

of course I have downloaded the two script files from the above website. However, it does not work, so is there some way to make it work, thanks.

**Comment by jaimerosales** [comment]
In order to run the viewer completely offline you will need to extract the entire bubble of the SVF file. Here is a sample you can take a look that does that. 
https://github.com/cyrillef/extract.autodesk.io Something I noticed is that the live version has been taking down, so you will need to debug your own version to make it work. Once you have an extracted SVF file you can use Sample 1 in this following Repo to do the offline viewing. 
https://github.com/Autodesk-Forge/forge-boilers.nodejs#project-1---viewer-offline 

Hope this helps. 
Cheers,
Jaime

**Comment by RollingEggOL** [comment]
Hi, Jaime

 Thanks for your reply. I have downloaded the offline sample at https://github.com/Autodesk-Forge/forge-boilers.nodejs#project-1---viewer-offline

the codes 
"<link rel="stylesheet" href="viewer-lib/style.css" type="text/css"/>
<script src="viewer-lib/three.min.js"></script>
  <script src="viewer-lib/viewer3D.js"></script>"
are mentioned in the html file. However no viewer-lib folder can be found in the projects. Then I created a new folder "viewer-lib" and downloaded style.css, viewer3D.js and three.min.js，but it still does not work. Your suggestion will be appreciated, would you please provide where I can find the corresponding "viewer-lib" folder and files there.  Thanks a lot.

best
xiaoqiang
